[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "nginx"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "nginx -c /app/nginx.conf -g 'daemon off;'"

